
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    assignees:
      - "guillermosipe"
    target-branch: "security"
    labels:
      - "GH-Actions Security dependencies"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Mexico_City"
    assignees:
      - "guillermosipe"
    target-branch: "security"
    labels:
      - "GH-Actions Security dependencies"
