//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.13 at 10:06:48 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://employersServices.exercise.com/Soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.exercise.employersServices.soap;
