//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.13 at 10:06:48 PM CST 
//


package com.exercise.employersServices.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmployerDetails" type="{http://employersServices.exercise.com/Soap}EmployerDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employerDetails"
})
@XmlRootElement(name = "saveEmployerRequest")
public class SaveEmployerRequest {

    @XmlElement(name = "EmployerDetails", required = true)
    protected EmployerDetails employerDetails;

    /**
     * Gets the value of the employerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerDetails }
     *     
     */
    public EmployerDetails getEmployerDetails() {
        return employerDetails;
    }

    /**
     * Sets the value of the employerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerDetails }
     *     
     */
    public void setEmployerDetails(EmployerDetails value) {
        this.employerDetails = value;
    }

}
